{
 "title": "New dashboard",
 "time": { "from": "2025-02-12T03:31:20.835Z", "to": "2025-02-26T03:31:20.835Z" },
 "panels": [
  {
   "title": "Transactions Tasks",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select \n    status, \n    count(status) as total\nfrom transactions\nwhere created_at >= now() - interval '30 days'\ngroup by status;"
    }
   ]
  },
  {
   "title": "Saga transactions",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select \n    status,\n    count(status) as total\nfrom tx_sagas \nwhere created_at >= now() - interval '30 days'\ngroup by status"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select * from tx_sagas \nORDER BY updated_at desc limit 100;"
    }
   ]
  },
  {
   "title": "Transactions with saga pattern",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "select \n    substring(tx_sagas.id::text from '^[^-]+') || '--' || transactions.event_name || '--' || transactions.status || '--' || tx_sagas.event_name || '--' || tx_sagas.status as saga,\n    transactions.updated_at as time\nfrom transactions \njoin tx_sagas on transactions.id = tx_sagas.transaction_id \norder by transactions.updated_at desc \nlimit 50;"
    }
   ]
  },
  {
   "title": "Transações",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "select event_name as \"Event\", event_id as \"EventId\", updated_at from transactions order by updated_at desc limit 100;"
    }
   ]
  }
 ]
}